inherit_from: .rubocop_todo.yml

require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-i18n

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

I18n/GetText:
  Enabled: false
I18n/RailsI18n:
  Enabled: true
  Exclude:
    - 'spec/**/*'
